pinkie_pie
dkotegov/seismograph pull request #3
Opened 2016-11-26 18:36 UTC by Ustimov

Тесты для

- seismograph/steps.py
- seismograph/xunit.py
- seismograph/tree.py

Команда

- Артем Устимов
- Марина Белянова
- Максим Галаганов
- Артем Шишикин

2016-11-27 21:54 UTC, dkotegov requested changes

2016-11-27 21:54 UTC, dkotegov commented on tests/tree.py
> +        self.assertEqual(len(self.buffer.getvalue().splitlines()), 12)
42

2016-11-27 21:54 UTC, dkotegov commented on tests/tree.py
> +        self.assertEqual(len(self.buffer.getvalue().splitlines()), 11)
А почему не проверяете содержимое?

2016-11-27 21:54 UTC, dkotegov commented on tests/tree.py
> +        self.assertEqual(len(self.buffer.getvalue().splitlines()), 8)
Magic number

2016-11-27 21:54 UTC, dkotegov commented on tests/steps.py
> +            self.assertIsInstance(e, ValueError)
Эта проверка всегда будет проходить

2016-11-29 07:25 UTC, Ustimov commented
 Исправлено

2016-12-14 01:32 UTC, dkotegov commented
Принято

2016-12-14 01:32 UTC, closed without merging