Команда 2D
dkotegov/seismograph pull request #4
Opened 2016-11-26 19:26 UTC by VitalyNikolaev

runnable.py покрытие на 83%, 90% можно добиться  тестируя только сам питон

2016-11-27 19:25 UTC, dkotegov commented
Тесты падают:
```
======================================================================
ERROR: test_register_function (tests.suite.TestRegisterCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Dmitry/TPHomeWork/stud/seismograph/tests/suite.py", line 339, in test_register_function
    signature = inspect.getargspec(created_class.test)
AttributeError: type object 'function' has no attribute 'test'

======================================================================
ERROR: test_register_static_function (tests.suite.TestRegisterCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Dmitry/TPHomeWork/stud/seismograph/tests/suite.py", line 354, in test_register_static_function
    signature = inspect.getargspec(created_class.test)
AttributeError: type object 'static_function' has no attribute 'test'

======================================================================
FAIL: test_build_one_box_from_two_tests (tests.suite.TestBuild)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Dmitry/TPHomeWork/stud/seismograph/tests/suite.py", line 613, in test_build_one_box_from_two_tests
    self.assertEqual(len(boxes[0]), 2)
AssertionError: 0 != 2

======================================================================
FAIL: runTest (tests.suite.TestRunSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Dmitry/TPHomeWork/stud/seismograph/tests/suite.py", line 625, in runTest
    self.assertEqual(len(self.result.successes), 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_get_map (tests.suite.TestSuiteObject)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Dmitry/TPHomeWork/stud/seismograph/tests/suite.py", line 237, in test_get_map
    'cls': CaseClass2,
AssertionError: {'CaseClass2': {'tests': {}, 'cls': <class 'tests.suite.CaseClass2'>}, 'CaseClas [truncated]... != {'CaseClass2': {'tests': {'test2': <unbound method CaseClass2.test2>}, 'cls': <c [truncated]...
- {'CaseClass': {'cls': <class 'tests.suite.CaseClass'>, 'tests': {}},
?                                                       --------------

+ {'CaseClass': {'cls': <class 'tests.suite.CaseClass'>,
+                'tests': {'test': <unbound method CaseClass.test>}},
-  'CaseClass2': {'cls': <class 'tests.suite.CaseClass2'>, 'tests': {}}}
?                                                         --------------

+  'CaseClass2': {'cls': <class 'tests.suite.CaseClass2'>,
+                 'tests': {'test2': <unbound method CaseClass2.test2>}}}

----------------------------------------------------------------------
Ran 135 tests in 0.062s

FAILED (failures=3, errors=2)```

2016-11-27 19:36 UTC, VitalyNikolaev commented
Так это тесты, которые уже были в папке, они не наши

2016-11-27 19:37 UTC, dkotegov commented
Они начали падать после ваших изменений :)

2016-11-27 19:53 UTC, dkotegov requested changes

2016-11-27 19:53 UTC, dkotegov commented on tests/runnable.py
> +        self.assertEqual(self.instance.mock_var, True)
assertTrue

2016-11-28 01:58 UTC, VitalyNikolaev commented
Все, теперь все ок!

2016-12-14 00:10 UTC, dkotegov commented
Принято

2016-12-14 00:10 UTC, closed without merging