Домашнее задание 5 - Дудцы
dkotegov/seismograph pull request #7
Opened 2016-11-27 17:27 UTC by maratkanov-a

2016-11-27 19:34 UTC, dkotegov commented
Тесты падают
```
======================================================================
ERROR: test_do (tests.tutu_tutu_tutu.PollingTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Dmitry/TPHomeWork/stud/seismograph/tests/tutu_tutu_tutu.py", line 38, in test_do
    do(requests.get)()()
  File "/Users/Dmitry/TPHomeWork/stud/seismograph/seismograph/ext/selenium/polling.py", line 49, in wrapped
    return f(*args, **kwargs)
TypeError: get() takes at least 1 argument (0 given)

----------------------------------------------------------------------
Ran 141 tests in 0.051s
```

2016-11-27 19:36 UTC, maratkanov-a commented
поэтому я и оставил комментарий, хочу сделать нормально, а не просто функцию, с которой не будет падать

2016-11-27 19:48 UTC, dkotegov requested changes

2016-11-27 19:48 UTC, dkotegov commented on tests/tutu_tutu_tutu.py
> +        do(requests.get)()()
Что вы хотите проверить этим тестом?

2016-11-27 19:48 UTC, dkotegov commented on tests/tutu_tutu_tutu.py
> +        self.assertRaises(ImportError, H)
И этим

2016-11-27 19:48 UTC, dkotegov commented on tests/tutu_tutu_tutu.py
> +        rule = re.compile(r'^{}$'.format(123))
Можно обойтись без регулярок

2016-11-27 19:48 UTC, dkotegov commented on tests/tutu_tutu_tutu.py
> +        mock_file.browser = {"FAKE": "FAKE"}
Копипаст можно вынести в setUp

2016-11-27 19:48 UTC, dkotegov commented on tests/tutu_tutu_tutu.py
> +        Router.__rules__ = {}
А это в tearDown

2016-11-27 19:48 UTC, dkotegov commented on tests/tutu_tutu_tutu.py
> +        self.assertEqual(res, attribute_by_alias('one'))
Чем эта проверка отличается от той, что на несколько строк выше?
Предположите случай, когда первая пройдет, а вторая нет?

2016-11-28 18:49 UTC, maratkanov-a commented
Поправил замечания

2016-11-28 18:50 UTC, maratkanov-a commented on tests/tutu_tutu_tutu.py
> +        self.assertEqual(res, attribute_by_alias('one'))
Исправил, имел в виду получение точного значения по точному ключу, в итоге получились одинаковые проверки

2016-12-13 23:47 UTC, dkotegov commented
Принято

2016-12-13 23:47 UTC, closed without merging