Пулл реквест
dkotegov/seismograph pull request #8
Opened 2016-11-28 01:22 UTC by temirlanKabylbekov

1. test_selenium_extension.py: не стали копипастить тесты для других локальных браузеров, написали тесты для одного - firefox

2. test_selenium_pageobject.py: покрытие не такое уже больше, 75%. Тестов в этом файле очень много.

2016-11-28 01:32 UTC, temirlanKabylbekov commented on seismograph/ext/selenium/extension.py
> +            'Capabilities for driver "{}" is not found'.format(driver_name),
была оппечатка в исходном коде

2016-11-28 01:34 UTC, temirlanKabylbekov commented on seismograph/ext/selenium/extension.py
> +            from seismograph.utils.common import waiting_for
Замокать функцию waiting_for, если она импортируется в тестируемом модуле относительно - не получилось, пришлось импортить абсолютно

2016-12-15 02:36 UTC, dkotegov requested changes

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_utils.py
> +        # TO CODE REVIEWER: не получилось замокать random.randint. What is the problem?
`@patch('seismograph.ext.selenium.utils.randint', return_value=500)`

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_extension.py
> +        self.assertTrue(browser.close.called and browser.quit.called)
Лучше разнести на 2 ассерта

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_extension.py
> +        )
assertIn

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_extension.py
> +        )
В случае падения такой ассерт вернет False is not True, чтобы понять что произошло надо будет запускать под отладчиком. Используйте assertNotIn

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_extension.py
> +    @patch('seismograph.utils.common.waiting_for')
`@patch('seismograph.ext.selenium.extension.waiting_for')`

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_extension.py
> +    # что-то подсказывает, что можно
Можно замокать "другую" функцию

2016-12-15 02:36 UTC, dkotegov commented on seismograph/ext/selenium/extension.py
> +            from seismograph.utils.common import waiting_for
Уберите

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_extension.py
> +    # одним браузером firefox
Получается:
-- Браузеры работают?
-- Не знаю, проверяем только firefox

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_extension.py
> +        self.assertEqual(s.is_running, False)
assertFalse

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_browser.py
> +    # from .proxy import WebDriverProxy?
Через `__name__` или seismograph.ext.selenium.proxy.WebDriverProxy

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_extension.py
> +        pass
Тест который ничего не проверяет

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_extension.py
> +    @unittest.skip('don\'t physically connect to remote browser (debug purpose)')
Зачем это здесь?

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_extension.py
> +    @unittest.skip('don\'t physically open local browser(debug purpose)')
?

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_pageobject.py
> +        pass
Не выглядит законченным :)

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_pageobject.py
> +        pass
?

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_pageobject.py
> +        # TODO
?

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_pageobject.py
> +        pass
И тут

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_pageobject.py
> +        with self.assertRaises(NotImplementedError):
Зачем это проверять?

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_pageobject.py
> +        # TODO use PropertyMock
:(

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_pageobject.py
> +            print(page.area)
Дебажные принты надо убрать

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_pageobject.py
> +            # self.assertEqual(page.area, 'proxy')
И дебажные комментарии ;)

2016-12-15 02:36 UTC, dkotegov commented on tests/test_selenium_pageobject.py
> +        pass
;(

2016-12-16 18:45 UTC, dkotegov commented
Принято

2016-12-16 18:45 UTC, closed without merging